const BASE_URL = "https://iiiqbets.com/pg-management";
export const MANAGER_LOGIN_URL = `${BASE_URL}/TENANT-login-API-managers-buildings.php`;
export const SINGLE_TENANT_ENQUIRY_DETAILS_URL = `${BASE_URL}/id-single-Tenant-Enquiry-Details-GET.php`;
export const ENQUIRY_TENANT_DETAILS_URL = `${BASE_URL}/Enquiry-Tenant-Details-GET.php`;
export const DELETE_TENANT_ENQUIRY_URL = `${BASE_URL}/delete-Tenant-Enquiry-API.php`;
export const UPDATE_TENANT_ENQUIRY_URL = `${BASE_URL}/update-Tenant-Enquiry-API.php`;
export const ENQUIRY_TENANT_POST_URL = `${BASE_URL}/Enquiry-Tenant-POST-API.php`;
export const TENANT_POST_URL = `${BASE_URL}/tenant_registration_POST_API_manager_mobile.php`;
export const TENANT_UPDATE_URL = `${BASE_URL}/update-TENANT-manager-buidling-API.php`;
